### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by yuu2lee4** [gwuhaolin/chrome-pool#4]
当我在centos7下面运行ChromePool.new()的时候，会报错：
(node:30838) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 chromeAlive listeners added. Use emitter.setMaxListeners() to increase limit
不管listenner数量设为多少，我发现listenner会一直增长直到报错，还有就是pool源代码里面执行到
chromePoll.chromeRunner = await launchChrome(Object.assign({}, chromeRunnerOptions, { port }));
就不执行了，看来是runner那边有bug

**Comment by yuu2lee4** [comment]
我追踪了一下，应该是chrome-runner/lib/runner.js的spawn有问题，被无限次执行了 导致chromeAlive listenner不断增长 并且没有relsove

**Comment by gwuhaolin** [comment]
是chrome 启动错误导致的。
你可以看下chrome输出的error日志里错误看看chrome启动错误的原因。
https://github.com/gwuhaolin/chrome-runner#chrome-log-files

**Comment by yuu2lee4** [comment]
可能是我这边环境的问题：
No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Comment by yuu2lee4** [comment]
runner.js里面flags.push('--disable-setuid-sandbox');好像过期了，改为：
if (process.platform === 'linux') {
     flags.push('--no-sandbox');
 }
就好了

**Comment by gwuhaolin** [comment]
ok，我fix下
