### ISSUE TITLE
chrome-pool能支持多少tab？

### ISSUE THREAD

**Issue by jacexh** [gwuhaolin/chrome-pool#5]
我之前从 https://chromedevtools.github.io/devtools-protocol/ 看到：
>Simultaneous protocol clients
>We currently do not support multiple clients connected to the protocol simultaneously. This includes opening DevTools while another client is connected. On the bug tracker, crbug.com/129539 follows the issue; you can star it for email updates.

我的理解是一个headless chrome只能支持一个web socket client接入，理论上不可能控制多tab？

**Comment by gwuhaolin** [comment]
tab越多占用内存越多。是可以同时控制多个tab的，我已经在实践中使用了。[chrome-render](https://github.com/gwuhaolin/chrome-render)是一个好例子。
