### ISSUE TITLE
puppeteer

### ISSUE THREAD

**Issue by yuu2lee4** [gwuhaolin/chrome-pool#9]
A Node library which provides a high-level API to control headless Chrome over the DevTools Protocol made by google.
https://github.com/GoogleChrome/puppeteer
谷歌自己出了个

**Comment by gwuhaolin** [comment]
chrome-pool 定位和 puppeteer 不一样。

puppeteer 提供了封装完好的常用功能，chrome-pool 只是集中管理浏览器的 tabs 去提高性能和节省资源，事实上 puppeteer 可以引入 chrome-pool 去提升性能。

chrome-pool 的目的是为了在需要高频执行一些功能时能有更快的响应速度和使用更少的资源。
用于服务端渲染的 [chrome-render](https://github.com/gwuhaolin/chrome-render) 项目就使用了 chrome-pool。

chrome-pool 不求大而全，只求做好它应该做的事情。

**Comment by yuu2lee4** [comment]
这个东西应该跟chrome-runner是一个性质
